version: '3.3'
services:
  identicon:
    links:
      -
  nginx:
    environment:
      - ENV=${ENV}
    # Пропишем какой образ мы хотим использовать
    image: nginx:latest
    # Назовем свой контейнер по красивому
    container_name: nginx
    # Проброс портов
    ports:
      - "5000:5000"
      - "443:44380"
    # Проброс папок
    volumes:
      - ./nginx/core:/etc/nginx/conf.d
      - ./app:/app
      - ./logs:/var/log/nginx/
      - ./html:/usr/share/nginx/html/
    # Укажем зависимости
    links:
      - php-$ENV
  php-dev:
    build: ./php_dev
    container_name: php-fpm-dev
    volumes:
      - ./app:/app
  php:

    # Билдим с помощью dockerfile указав директорию где он лежит
    build: ./php
    container_name: php-fpm
    volumes:
      - ./app:/app