version: '3.3'
services:
  identicon:
    build:
      context: .
      dockerfile: ./dev/Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
      - "443:44380"
    links:
      - composer
      - dnmonster
  composer:
    image: composer:latest
    volumes:
      - ./app:/app
    command: bash -c 'composer dump-autoload --no-scripts && composer update'
  dnmonster:
    image: amouat/dnmonster:1.0
    ports:
      - "9991:8080"