version: '3.3'
services:
#  web
  identidock:
    build:
      context: .
      dockerfile: ./dev/Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
      - "44380:443"
    links:
      - composer
      - dnmonster
      - redis
  composer:
    image: composer:latest
    volumes:
      - ./app:/app
    command: bash -c 'composer dump-autoload --no-scripts && composer update'
  dnmonster:
    image: amouat/dnmonster:1.0
    ports:
      - "9991:8080"
  redis:
    image: redis:3.0