identidock:
  build: .
  ports:
    - "5001:5001"
    - "44380:443"
  environment:
    ENV: PROD
  volumes:
    - $PWD/app:/app
  links:
    - dnmonster
    - redis
  
dnmonster:
  image: amouat/dnmonster:1.0
  ports:
    - "9991:8080"

redis:
  image: redis:3.0

composer:
  image: composer:latest
  volumes:
    - $PWD/app:/app
  command: 'true'
