proxy:
  image: proxy:0.1
  links:
    - identidock
  ports:
    - "8181:81"
  environment:
    - NGINX_HOST=localhost
    - NGINX_PROXY=http://identidock:5001

identidock:
  build: .
  ports:
  - "5001:5001"
  - "44380:443"
  environment:
    ENV: PROD
  volumes:
  - $PWD/app:/app
  links:
  - dnmonster
  - redis

dnmonster:
  image: amouat/dnmonster:1.0
  ports:
  - "9991:8080"

redis:
  image: redis:3.0

logspout:
  image: amouat/logspout-logstash
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  ports:
    - "8000:80"
  links:
    - logstash
  command: logstash://logstash:5000

logstash:
  image: logstash:1.5
  volumes:
    - ./logstash.conf:/etc/logstash.conf
  environment:
    LOGSPOUT: ignore
  command: -f /etc/logstash.conf

composer:
  image: composer:latest
  volumes:
  - $PWD/app:/app
  command: 'true'